# config
cover: /images/cover.jpg
logo: 
bio: 'Make things or make things happend'

# Content
excerpt_link: 更多

# Miscellaneous
rss: 

copyrightdate: 2021


weibo: https://weibo.com/u/5400818178

google_analytics: UA-140230223-1
